### ISSUE TITLE
search for code

### ISSUE THREAD

**Issue by mitao-cat** [dgliu/RecSys21_DIB#1]
Hi, I'm a Ph.D. student at the University of Science and Technology of China, my interest domains are the Recommender system, debiased learning, and causal inference.
We want to cite your great paper <Mitigating Confounding Bias in Recommendation via information Bottleneck> at RecSys21 and leverage your code. When can you release your implement code?
Thanks!

**Comment by dgliu** [comment]
I have already replied to your group about the implementation details. If there are any unresolved issues, please feel free to contact me.

**Comment by dgliu** [comment]
We apologize again for the previous delay and the code has been released.
So I will close this issue.
